"""bank connections

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 11:14:11.060404
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('blz', sa.String(length=8), nullable=False),
    sa.Column('server_url', sa.String(length=255), nullable=False),
    sa.Column('login_name', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('pin_encrypted', sa.Text(), nullable=True),
    sa.Column('tan_mechanism', sa.String(length=10), nullable=True),
    sa.Column('tan_medium', sa.String(length=100), nullable=True),
    sa.Column('client_state', sa.LargeBinary(), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_connections_user_id'), ['user_id'], unique=False)

    op.create_table('bank_account_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('subaccount', sa.String(length=30), nullable=False),
    sa.Column('blz', sa.String(length=8), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('sync_from', sa.Date(), nullable=True),
    sa.Column('synced_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connection_id'], ['bank_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'iban', 'account_number', 'subaccount')
    )
    with op.batch_alter_table('bank_account_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_account_links_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_account_links_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_account_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_bank_account_links_connection_id'))

    op.drop_table('bank_account_links')
    with op.batch_alter_table('bank_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_connections_user_id'))

    op.drop_table('bank_connections')
    # ### end Alembic commands ###
