"""credit cards and splits

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-04 11:56:14.551057
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_splits_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_splits_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_splits_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), server_default='checking', nullable=False))
        batch_op.add_column(sa.Column('settlement_pattern', sa.String(length=100), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('settlement_pattern')
        batch_op.drop_column('kind')

    with op.batch_alter_table('transaction_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_splits_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_splits_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_splits_category_id'))

    op.drop_table('transaction_splits')
    # ### end Alembic commands ###
